<#
.SYNOPSIS
  Copies everything you typically need for GitHub/submission into one folder: github_upload_bundle/

.DESCRIPTION
  Run from repo root:
    powershell -ExecutionPolicy Bypass -File scripts/build_github_bundle.ps1

  Then either:
  - Zip `github_upload_bundle` and upload it, or
  - `cd github_upload_bundle`, `git init`, add remote, push a minimal repo

  This folder is gitignored in the main repo to avoid duplicating every file twice.
#>

$ErrorActionPreference = "Stop"
$Root = Resolve-Path (Join-Path $PSScriptRoot "..")
$Dest = Join-Path $Root "github_upload_bundle"

Write-Host "Project root: $Root"
Write-Host "Bundle dest:  $Dest"

if (Test-Path $Dest) {
  Remove-Item $Dest -Recurse -Force
}
New-Item -ItemType Directory -Path $Dest -Force | Out-Null

function Get-RobocopyExe {
  $candidates = @(
    (Join-Path $env:SystemRoot "System32\robocopy.exe"),
    (Join-Path $env:WINDIR "System32\robocopy.exe")
  )
  foreach ($c in $candidates) {
    if (Test-Path -LiteralPath $c) { return $c }
  }
  return $null
}

function Copy-TreeNoRobocopy {
  param([string]$Source, [string]$Target, [string[]]$ExcludeDirs)
  if (-not (Test-Path $Source)) { return }
  New-Item -ItemType Directory -Path $Target -Force | Out-Null
  Get-ChildItem -LiteralPath $Source -Force | ForEach-Object {
    if ($_.PSIsContainer) {
      if ($ExcludeDirs -contains $_.Name) { return }
      Copy-TreeNoRobocopy -Source $_.FullName -Target (Join-Path $Target $_.Name) -ExcludeDirs $ExcludeDirs
    } else {
      Copy-Item -LiteralPath $_.FullName -Destination (Join-Path $Target $_.Name) -Force
    }
  }
}

function Copy-RepoDir {
  param([string]$RelativePath, [string[]]$ExcludeDirs = @("__pycache__", ".pytest_cache"))
  $src = Join-Path $Root $RelativePath
  if (-not (Test-Path $src)) {
    Write-Warning "Skip missing: $RelativePath"
    return
  }
  $dst = Join-Path $Dest $RelativePath
  New-Item -ItemType Directory -Path $dst -Force | Out-Null
  $rc = Get-RobocopyExe
  if ($rc) {
    $rcArgs = @($src, $dst, "/E", "/NFL", "/NDL", "/NJH", "/NJS", "/NC", "/NS")
    if ($ExcludeDirs.Count -gt 0) {
      $rcArgs += "/XD"
      $rcArgs += $ExcludeDirs
    }
    & $rc @rcArgs | Out-Null
    if ($LASTEXITCODE -ge 8) {
      throw "robocopy failed for $RelativePath (code $LASTEXITCODE)"
    }
  } else {
    Copy-TreeNoRobocopy -Source $src -Target $dst -ExcludeDirs $ExcludeDirs
  }
}

function Copy-TreeFull {
  param([string]$Source, [string]$Target)
  if (-not (Test-Path $Source)) { return }
  New-Item -ItemType Directory -Path $Target -Force | Out-Null
  $rc = Get-RobocopyExe
  if ($rc) {
    & $rc $Source $Target /E /NFL /NDL /NJH /NJS /NC /NS | Out-Null
    if ($LASTEXITCODE -ge 8) { throw "robocopy failed: $Source" }
  } else {
    Copy-TreeNoRobocopy -Source $Source -Target $Target -ExcludeDirs @()
  }
}

# --- Python API & pipeline ---
Copy-RepoDir "api" @("__pycache__")
Copy-RepoDir "modeling" @("__pycache__")
Copy-RepoDir "data_processing" @("__pycache__")
Copy-RepoDir "data_ingestion" @("__pycache__")

# --- Frontends (no node_modules / build output) ---
Copy-RepoDir "frontend1" @("node_modules", ".next", "out", "dist")
Copy-RepoDir "frontend\vite-project" @("node_modules", "dist")

# --- Data: processed + NOAA + main USGS daily (adjust if your files differ) ---
$dataProcessed = Join-Path $Dest "data\processed"
New-Item -ItemType Directory -Path $dataProcessed -Force | Out-Null
foreach ($f in @("clean_data.csv", "features.csv")) {
  $p = Join-Path $Root "data\processed\$f"
  if (Test-Path $p) { Copy-Item $p $dataProcessed -Force }
}

$noaaSrc = Join-Path $Root "data\raw\noaa"
if (Test-Path $noaaSrc) {
  $noaaDst = Join-Path $Dest "data\raw\noaa"
  Copy-TreeFull -Source $noaaSrc -Target $noaaDst
}

$usgsSrc = Join-Path $Root "data\raw\usgs"
if (Test-Path $usgsSrc) {
  $usgsDst = Join-Path $Dest "data\raw\usgs"
  Copy-TreeFull -Source $usgsSrc -Target $usgsDst
}

# --- Models & metrics ---
$modelsDst = Join-Path $Dest "models"
New-Item -ItemType Directory -Path $modelsDst -Force | Out-Null
foreach ($f in @("model.pkl", "lgbm_model.pkl")) {
  $p = Join-Path $Root "models\$f"
  if (Test-Path $p) { Copy-Item $p $modelsDst -Force }
}

$resultsSrc = Join-Path $Root "results"
if (Test-Path $resultsSrc) {
  $resultsDst = Join-Path $Dest "results"
  New-Item -ItemType Directory -Path $resultsDst -Force | Out-Null
  Get-ChildItem $resultsSrc -Filter "*.json" -File | ForEach-Object {
    Copy-Item $_.FullName $resultsDst -Force
  }
}

# --- Root files ---
foreach ($f in @("requirements.txt", "run_pipeline.py", "datasets.md", "README.md")) {
  $p = Join-Path $Root $f
  if (Test-Path $p) { Copy-Item $p $Dest -Force }
}

# --- README for the bundle ---
$readme = @"
# GitHub / submission bundle

This folder was generated by **scripts/build_github_bundle.ps1** (run from the project root).

## What to do next

### Option A — Push your full project (recommended)
From the **main repository root** (parent of this folder), use normal Git:

```bash
git add -A
git status
git commit -m "Your message"
git push
```

Do **not** commit this generated copy inside the same repo unless you want duplicate files.

### Option B — Submit only this folder
1. Zip **everything inside** `github_upload_bundle` (this folder).
2. Upload the zip per your course instructions, **or**
3. Create a **new** empty GitHub repo, unzip into it, then:

```bash
git init
git add -A
git commit -m "Initial commit"
git branch -M main
git remote add origin https://github.com/YOU/REPO.git
git push -u origin main
```

## After unzipping / cloning

- **Backend:** Python venv, `pip install -r requirements.txt`, then e.g. `uvicorn api.app:app --reload` from the folder that contains `api/`.
- **frontend1:** `cd frontend1`, `pnpm install` or `npm install`, then `pnpm dev` or `npm run dev`.
- **vite-project:** `cd frontend/vite-project`, `npm install`, `npm run dev`.

Regenerate this bundle any time from the **parent** project:

```powershell
powershell -ExecutionPolicy Bypass -File scripts/build_github_bundle.ps1
```

Generated: $(Get-Date -Format "yyyy-MM-dd HH:mm")
"@
$readme | Set-Content -Path (Join-Path $Dest "README.md") -Encoding utf8

Write-Host ""
Write-Host "Done. Contents:" -ForegroundColor Green
Get-ChildItem $Dest | Format-Table Name, Mode -AutoSize
Write-Host "Next: zip github_upload_bundle or follow README.md inside it."

# robocopy sets exit code 0–7 on success; avoid failing the script with 1
exit 0
